// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvhmidzgohpxtkqgvndm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2aG1pZHpnb2hweHRrcWd2bmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDQxMzMsImV4cCI6MjA2NTQ4MDEzM30.u4mq7-mWPf_AJTE3UKIGVgIZcUAHa7n9F2vNch8bLCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);